// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbCjLKEJokILUGpbrD0RdLhkA-kA2LD1U',
    appId: '1:721890670912:web:0a60e694b320b30abbe2a5',
    messagingSenderId: '721890670912',
    projectId: 'anjastore-eba65',
    authDomain: 'anjastore-eba65.firebaseapp.com',
    storageBucket: 'anjastore-eba65.appspot.com',
    measurementId: 'G-3R43P22C0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB79mkYvHbvpClGiyjQTthaSPOYIjURM6o',
    appId: '1:721890670912:android:b0f617474b6682babbe2a5',
    messagingSenderId: '721890670912',
    projectId: 'anjastore-eba65',
    storageBucket: 'anjastore-eba65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4I8f4rpXPFgn98O0uZWUztaXpqc-oI-Q',
    appId: '1:721890670912:ios:830cb2a94c8e85d3bbe2a5',
    messagingSenderId: '721890670912',
    projectId: 'anjastore-eba65',
    storageBucket: 'anjastore-eba65.appspot.com',
    iosClientId: '721890670912-4o733ladrjkrfek2d6m2llhd96cihq29.apps.googleusercontent.com',
    iosBundleId: 'com.example.anjastore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4I8f4rpXPFgn98O0uZWUztaXpqc-oI-Q',
    appId: '1:721890670912:ios:830cb2a94c8e85d3bbe2a5',
    messagingSenderId: '721890670912',
    projectId: 'anjastore-eba65',
    storageBucket: 'anjastore-eba65.appspot.com',
    iosClientId: '721890670912-4o733ladrjkrfek2d6m2llhd96cihq29.apps.googleusercontent.com',
    iosBundleId: 'com.example.anjastore',
  );
}
